# Generated by Django 4.2.11 on 2024-03-26 15:14

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0003_professor_past_teaching_lessons_and_more"),
        ("course", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Term",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=256, verbose_name="نام ترم")),
                (
                    "start_selection_time",
                    models.DateTimeField(verbose_name="زمان شروع انتخاب واحد"),
                ),
                (
                    "end_selection_time",
                    models.DateTimeField(verbose_name="زمان پایان انتخاب واحد"),
                ),
                (
                    "class_start_time",
                    models.DateTimeField(verbose_name="زمان شروع کلاس ها"),
                ),
                (
                    "class_end_time",
                    models.DateTimeField(verbose_name="زمان پایان کلاس ها"),
                ),
                (
                    "doped_added_start_time",
                    models.DateTimeField(verbose_name="زمان شروع حذف و اضافه"),
                ),
                (
                    "doped_added_end_time",
                    models.DateTimeField(verbose_name="زمان پایان حذف و اضافه"),
                ),
                (
                    "emergency_removal_end_time",
                    models.DateTimeField(verbose_name="زمان پایان حذف اضطراری"),
                ),
                (
                    "exam_start_time",
                    models.DateTimeField(verbose_name="زمان شروع امتحانات"),
                ),
                ("term_end_time", models.DateTimeField(verbose_name="زمان اتمام ترم")),
                (
                    "course_lists",
                    models.ManyToManyField(
                        related_name="term_course_lists",
                        to="course.course",
                        verbose_name="لیست دروس ترمی",
                    ),
                ),
                (
                    "professors",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="term_professor",
                        to="accounts.professor",
                        verbose_name="اساتید",
                    ),
                ),
                (
                    "students",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="term_students",
                        to="accounts.student",
                        verbose_name="دانشجوها",
                    ),
                ),
            ],
        ),
    ]
