# Generated by Django 4.2.11 on 2024-03-28 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0003_alter_subject_corequisite_alter_subject_prerequisite"),
        ("term", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="term",
            name="course_lists",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="term_course_lists",
                to="course.course",
                verbose_name="لیست دروس ترمی",
            ),
        ),
    ]
