# Generated by Django 4.2.11 on 2024-03-28 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_alter_student_military_service_status_and_more"),
        ("term", "0002_alter_term_course_lists"),
    ]

    operations = [
        migrations.AlterField(
            model_name="term",
            name="students",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="term_students",
                to="accounts.student",
                verbose_name="دانشجوها",
            ),
        ),
    ]
