# Generated by Django 4.2.11 on 2024-04-07 17:33

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0013_alter_student_avatar"),
        ("term", "0005_term_year_unitregisterrequest"),
    ]

    operations = [
        migrations.CreateModel(
            name="BusyStudyingRequest",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "request_state",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "pending"), (2, "accepted"), (3, "rejected")],
                        default=1,
                        verbose_name="وضعیت درخواست",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assistant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="busy_studying_request_assistant",
                        to="accounts.educationalassistant",
                        verbose_name="معاون آموزشی",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="busy_studying_request_student",
                        to="accounts.student",
                        verbose_name="دانشجو",
                    ),
                ),
            ],
        ),
    ]
