# Generated by Django 4.2.11 on 2024-04-08 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("term", "0006_busystudyingrequest"),
    ]

    operations = [
        migrations.AlterField(
            model_name="term",
            name="name",
            field=models.CharField(
                blank=True, max_length=256, null=True, verbose_name="نام ترم"
            ),
        ),
    ]
