# Generated by Django 4.2.11 on 2024-04-09 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("term", "0007_alter_term_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="unitregisterrequest",
            name="term",
            field=models.ForeignKey(
                default="aa95d526-d0c2-4968-91df-038a25d48033",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="unit_request_term",
                to="term.term",
                verbose_name="ترم ",
            ),
            preserve_default=False,
        ),
    ]
