# Generated by Django 4.2.11 on 2024-04-12 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('term', '0009_unitregisterrequest_supervisor'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitregisterrequest',
            name='emergency_removal_request',
            field=models.BooleanField(default=False, verbose_name='حذف اضطراری درس'),
        ),
    ]
