# Generated by Django 4.2.11 on 2024-04-12 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('term', '0010_unitregisterrequest_emergency_removal_request'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unitregisterrequest',
            name='emergency_removal_request',
        ),
    ]
