# Generated by Django 4.2.11 on 2024-04-12 13:13

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_scoretable'),
        ('accounts', '0016_alter_studenttermaverage_student_and_more'),
        ('term', '0011_remove_unitregisterrequest_emergency_removal_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyRemoval',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request_state', models.PositiveSmallIntegerField(choices=[(1, 'pending'), (2, 'accepted'), (3, 'rejected')], default=1, verbose_name='وضعیت درخواست')),
                ('reason_rejected', models.TextField(blank=True, null=True, verbose_name='دلیل رد درخواست')),
                ('assistant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_removal_assistant', to='accounts.educationalassistant', verbose_name='معاون آموزشی')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_removal_course', to='course.course', verbose_name='درس')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_removal_student', to='accounts.student', verbose_name='دانشجو')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_removal_term', to='term.term', verbose_name='ترم')),
            ],
        ),
    ]
