# Generated by Django 4.2.11 on 2024-03-26 15:14

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0002_educationalassistant_faculty_professor_faculty_and_more"),
        ("faculty", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=256)),
                (
                    "number_of_course",
                    models.PositiveIntegerField(verbose_name="تعداد واحد درس"),
                ),
                (
                    "course_type",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "basic"), (2, "specialized"), (3, "general")],
                        default=1,
                        verbose_name="نوع درس",
                    ),
                ),
                (
                    "mandatory",
                    models.IntegerField(
                        default=1, verbose_name="وضعیت اجباری بودن یا نبودن درس"
                    ),
                ),
                (
                    "corequisite",
                    models.ManyToManyField(
                        related_name="subject_corequisite",
                        to="course.subject",
                        verbose_name="دروس همنیاز",
                    ),
                ),
                (
                    "prerequisite",
                    models.ManyToManyField(
                        related_name="subject_prerequisite",
                        to="course.subject",
                        verbose_name="دروس پیش نیاز",
                    ),
                ),
                (
                    "provider_faculty",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subject_faculty",
                        to="faculty.faculty",
                        verbose_name="دانشکده ارائه دهنده",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "class_id",
                    models.PositiveIntegerField(unique=True, verbose_name="شماره کلاس"),
                ),
                (
                    "day",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "saturday"),
                            (2, "sunday"),
                            (3, "monday"),
                            (4, "tuesday"),
                            (5, "wednesday"),
                            (6, "thursday"),
                            (7, "friday"),
                        ],
                        default=1,
                        verbose_name="انتخاب روز",
                    ),
                ),
                ("time", models.TimeField(verbose_name="زمان کلاس")),
                ("capacity", models.PositiveIntegerField(verbose_name="ظرفیت")),
                ("exam_time", models.DateTimeField(verbose_name="تاریخ و زمان امتحان")),
                (
                    "exam_class_id",
                    models.PositiveIntegerField(verbose_name="شماره کلاس امتحان"),
                ),
                (
                    "professor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="course_professor",
                        to="accounts.professor",
                        verbose_name="استاد",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="course_subject",
                        to="course.subject",
                        verbose_name="درس مصوب",
                    ),
                ),
            ],
        ),
    ]
