# Generated by Django 4.2.11 on 2024-03-28 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subject",
            name="corequisite",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="subject_corequisite",
                to="course.subject",
                verbose_name="دروس همنیاز",
            ),
        ),
        migrations.AlterField(
            model_name="subject",
            name="prerequisite",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="subject_prerequisite",
                to="course.subject",
                verbose_name="دروس پیش نیاز",
            ),
        ),
    ]
