# Generated by Django 4.2.11 on 2024-04-02 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("term", "0004_remove_term_course_lists_remove_term_professors_and_more"),
        ("course", "0003_alter_subject_corequisite_alter_subject_prerequisite"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="term",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="course_term",
                to="term.term",
                verbose_name="ترم جاری",
            ),
        ),
    ]
