# Generated by Django 4.2.11 on 2024-03-26 14:33

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Faculty",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=256, verbose_name="نام دانشکده")),
                (
                    "phone",
                    models.CharField(
                        max_length=256, unique=True, verbose_name="شماره دانشکده"
                    ),
                ),
                ("address", models.TextField(verbose_name="آدرس دانشکده")),
                (
                    "university",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="faculty_university",
                        to="accounts.university",
                        verbose_name="انتخاب دانشگاه",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Major",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=256, verbose_name="نام رشته")),
                (
                    "department",
                    models.CharField(max_length=256, verbose_name="گروه آموزشی"),
                ),
                (
                    "number_of_units",
                    models.PositiveBigIntegerField(verbose_name="تعداد واحد"),
                ),
                (
                    "education_level",
                    models.CharField(max_length=256, verbose_name="مقطع تحصیلی"),
                ),
                (
                    "faculty",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="major_faculty",
                        to="faculty.faculty",
                        verbose_name="انتخاب دانشکده",
                    ),
                ),
            ],
        ),
    ]
