# Generated by Django 4.2.11 on 2024-03-26 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("faculty", "0001_initial"),
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="educationalassistant",
            name="faculty",
            field=models.OneToOneField(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="educational_assistant_faculty",
                to="faculty.faculty",
                verbose_name="انتخاب دانشکده",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="professor",
            name="faculty",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="professor_faculty",
                to="faculty.faculty",
                verbose_name="انتخاب دانشکده",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="professor",
            name="major",
            field=models.OneToOneField(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="professor_major",
                to="faculty.major",
                verbose_name="رشته",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="student",
            name="faculty",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student_faculty",
                to="faculty.faculty",
                verbose_name="انتخاب دانشکده",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="student",
            name="major",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student_major",
                to="faculty.major",
                verbose_name="انتخاب رشته تحصیلی",
            ),
            preserve_default=False,
        ),
    ]
