# Generated by Django 4.2.11 on 2024-03-26 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0001_initial"),
        ("accounts", "0002_educationalassistant_faculty_professor_faculty_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="professor",
            name="past_teaching_lessons",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="professor_past_teaching_lessons",
                to="course.course",
                verbose_name="دروس تدریس شده",
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="lessons_in_progress",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="student_lessons_in_progress",
                to="course.course",
                verbose_name="دروس در حال گذراندن",
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="passed_lessons",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="student_passed_lessons",
                to="course.course",
                verbose_name="دروس پاس شده",
            ),
        ),
    ]
