# Generated by Django 4.2.11 on 2024-03-28 20:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_alter_student_military_service_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="educationalassistant",
            name="educational_assistant",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="EducationalAssistant_user_role",
                to=settings.AUTH_USER_MODEL,
                verbose_name="نام کاربری",
            ),
        ),
        migrations.AlterField(
            model_name="itmanager",
            name="IT_manager",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ITManager_user_role",
                to=settings.AUTH_USER_MODEL,
                verbose_name="نام کاربری",
            ),
        ),
        migrations.AlterField(
            model_name="professor",
            name="professor",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="professor_user_role",
                to=settings.AUTH_USER_MODEL,
                verbose_name="نام کاربری",
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="student",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student_user_role",
                to=settings.AUTH_USER_MODEL,
                verbose_name="نام کاربری",
            ),
        ),
    ]
