# Generated by Django 4.2.11 on 2024-03-31 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_alter_student_supervisor"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="educationalassistant",
            name="assistant",
        ),
        migrations.RemoveField(
            model_name="educationalassistant",
            name="educational_assistant",
        ),
        migrations.AddField(
            model_name="educationalassistant",
            name="professor",
            field=models.OneToOneField(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="EducationalAssistant_assistant",
                to="accounts.professor",
                verbose_name="آیدی استاد",
            ),
            preserve_default=False,
        ),
    ]
