# Generated by Django 4.2.11 on 2024-04-02 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("faculty", "0001_initial"),
        ("accounts", "0008_rename_professor_educationalassistant_assistant"),
    ]

    operations = [
        migrations.AlterField(
            model_name="professor",
            name="major",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="professor_major",
                to="faculty.major",
                verbose_name="رشته",
            ),
        ),
    ]
