# Generated by Django 4.2.11 on 2024-04-02 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("term", "0004_remove_term_course_lists_remove_term_professors_and_more"),
        ("accounts", "0009_alter_professor_major"),
    ]

    operations = [
        migrations.AddField(
            model_name="professor",
            name="term",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="professor_term",
                to="term.term",
                verbose_name="ترم جاری",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="student",
            name="term",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student_term",
                to="term.term",
                verbose_name="ترم جاری",
            ),
            preserve_default=False,
        ),
    ]
