# Generated by Django 4.2.11 on 2024-04-02 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0004_alter_course_term"),
        ("accounts", "0011_otpcode_code_expire"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="lessons_in_progress",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="student_lessons_in_progress",
                to="course.subject",
                verbose_name="دروس در حال گذراندن",
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="passed_lessons",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="student_passed_lessons",
                to="course.subject",
                verbose_name="دروس پاس شده",
            ),
        ),
    ]
