# Generated by Django 4.2.11 on 2024-04-08 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0015_studenttermaverage_term_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studenttermaverage",
            name="student",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student_term_average_student",
                to="accounts.student",
                verbose_name="دانشجو",
            ),
        ),
        migrations.AlterField(
            model_name="studenttermaverage",
            name="term_number",
            field=models.PositiveIntegerField(default=0, verbose_name="شماره ترم"),
        ),
    ]
